### ISSUE TITLE
Remapping tmux-sessionist default bindings?

### ISSUE THREAD

**Issue by erlandsona** [tmux-plugins/tmux-sessionist#10]
With iTerm being able to send +esc sequences my Meta key started working in the terminal and I wanted to be able to bind M-C to create a new session similarly to how I've bound M-c to create a new window.

Thoughts?

**Comment by bruno-** [comment]
Hey,
you should be able to remap default key bindings with something like this in `.tmux.conf`:

    # prefix + M-C for creating new session
    set -g @sessionist-new 'M-C'

You can find the list of all the options in [this file](https://github.com/tmux-plugins/tmux-sessionist/blob/master/sessionist.tmux).

**Comment by erlandsona** [comment]
Yes except that I'd like to be able to do it without a prefix key... Call me crazy but I hate the default TMUX prefix and also the ctrl-a alternative. I prefer not to have to use a prefix at all so I remapped all of the default TMUX bindings using iTerms esc+ setting and setting capslock to option (meta/esc+) then setting all of the tmux bindings with the -n flag (no prefix) it actually works fantastic because I could never get any of my vim bindings to work properly with the meta key so for the most part it never conflicts with any other terminal bindings!

That said, I'm looking more for something like...
bind-key -n M-C @sessionist-new

Thoughts? I tried just doing a new session from the command-prompt but that didn't work either?

**Comment by bruno-** [comment]
Ah ok, I get it now.
I'm not sure if this will be supported unless more users start using tmux in this way.

You can try the following solution:

- install this plugin
- manually bind its script to your key. In `.tmux.conf`: `bind-key -n M-C run ~/.tmux/plugins/tmux-sessionist/scripts/new_session_prompt.sh`.

I just tried this and it seems to work. It's not as nice as `bind-key -n M-C @sessionist-new`, but it should do the job.

> I tried just doing a new session from the command-prompt but that didn't work either?

I know! Creating and managing sessions with tmux is messed up. That's why this plugin was created.

**Comment by erlandsona** [comment]
Oh! so basically just call the appropriate scripts? That worked!!! Thank you so much! I realize I'm probably the only person in the world who's anal enough to rebind all the default tmux bindings to take advantage of the no-prefix option but you have to admit the whole prefix binding gets super annoying to hit everytime you just want to switch a pane or something?

**Comment by erlandsona** [comment]
Thank you so much for the tip! I've been wondering how to do that for a while now!

**Comment by bruno-** [comment]
> Oh! so basically just call the appropriate scripts?

Yes, all the plugin keybindings work that way.

> the only person in the world who's anal enough to rebind all the default tmux bindings to take advantage of the no-prefix option

Why don't you make a plugin out of it and see if there are other people that like your idea.

> but you have to admit the whole prefix binding gets super annoying to hit everytime you just want to switch a pane or something

Frankly, this never occurred to me until you brought it up in this issue. I guess I'm quite used to how things work by default.

I'm glad things work for you. I'm going to close this issue, but feel free to let me know if you need help with anything else.

**Comment by erlandsona** [comment]
Yeah this one's definitely closed! Thank you so much for the help. As far as creating a plugin...

I'd love to share my setup with other people because I've spent way more time than I'd like to admit getting it right but I don't know where to start with creating a plugin? I have my dotfiles on my github repo... Plus I don't have the resources or the patience to try it on different systems and setups? I'm on OSX 10.10 with a MBP and iTerm2 so I don't know how portable my solutions would be for other systems? Yes I have VirtualBox but it takes so long to get setup and I don't have the right hardware for the systems that I'd be configuring for?

Any thoughts?

**Comment by bruno-** [comment]
Hey,
I suggest starting small with your own plugin. It does not have to be supported on platforms other than your mac (even though it will probably just work everywhere).

Here's the simplest tmux plugin:

- create a file `plugin_name.tmux` (`*.tmux` file extension is important) with content (from your `tmux.conf`)

        #!/usr/bin/env bash
        tmux bind-key -n M-c command-prompt -p "Name of new window: " "new-window -c '#{pane_current_path}' -n '%%'"

- make a git repo out of this, commit and push it to github
- the plugin can now be installed with `set -g @plugin 'erlandsona/tmux-plugin-name'`
- if things work, continue adding other key bindings to the `plugin_name.tmux` file

Let me know if you need more help with this, I'd be happy to help. Heck, I'd do this work myself, but I don't want to own the repo I'm not actually using.

**Comment by erlandsona** [comment]
Actually if you wouldn't mind contributing I'd greatly appreciate it! I've never made a plugin before I'm so excited!!! Haha OpenSource FTW! Here's the repo... I added you as a contributor if that's cool? https://github.com/erlandsona/meta_prefixor.git

Basically I just copied and pasted the bindings I have from my .tmux.conf which maybe aren't as generic as they could be and I deleted some of the default tmux bindings because I didn't find them useful in my setup. There's a couple issues I see with this setup which is first that if this gets added as a plugin the call to unbind-key -a will wipe any preexisting settings the user has defined, right? Or do the plugins get loaded up first? How could I specify that for this particular plugin?

If this works and it actually provides some use for TMUX users I'd be stoked! That would be way cool to have people from all over the world collaborating for better terminal editing workflows!

**Comment by erlandsona** [comment]
Sorry nuther couple questions... do you know how to get the session names to auto prepend a session id? When I hit M-g it runs the script perfectly but when I run M-X then check the list it doesn't re-address the session ids? I'm currently hardcoding them but they're really useful for switching sessions quickly by just typing in a number for the session. And the default M-() bindings are nice moving to the next/prev session quickly but when you need to switch contexts it's nice to be able to see a description next to an id.

Thoughts?

**Comment by bruno-** [comment]
>  if this gets added as a plugin the call to unbind-key -a will wipe any preexisting settings the user has defined, right?

Yes, all key bindings will be deleted. This seems pretty intrusive though. I think it would be better to leave the decision to delete everything to the user, maybe add a note about this to the readme.

> Or do the plugins get loaded up first?

No, plugins are loaded last.

> If this works and it actually provides some use for TMUX users I'd be stoked!

It's up to you to spread the word. Once you verify things work, you might want to announce the plugin [here](https://www.reddit.com/r/tmux).
