### ISSUE TITLE
Rename existing session

### ISSUE THREAD

**Issue by hex0cter** [tmux-plugins/tmux-sessionist#20]
Hi!

Thanks for the great plugin, I really love it! It just happens that sometime I would like to rename an existing session. Is there a way to do it?

Best Regards,
Daniel Han

**Comment by bruno-** [comment]
Hi,

yes, tmux itself has a support for this. The key binding is `prefix +
$` and you'll get a prompt to enter new session name.

**Comment by hex0cter** [comment]
Ah, I didn't know it. Sorry for this and thanks for the help!
