### ISSUE TITLE
Error when switching sessions with `prefix + g`

### ISSUE THREAD

**Issue by bruno-** [tmux-plugins/tmux-sessionist#8]
David Melech reported via email:

> error can be reproduced when try choice session (prefix + g).
> For example: when have two sessions called 'dev' (current) and 'chat' and wanna switch to 'chat' I will press prefix + g and type 'chat' (without apostrophe ofc).
> When it done - session switched, but menu doesn't close (need press Esc) and list of available session duplicated. (two 'dev', 'chat')

Btw. he's using tmux from the [hooks branch](http://sourceforge.net/p/tmux/tmux-code/ci/hooks/tree/).

**Comment by petermehle** [comment]
I have similar problem, but when I try to switch, the menu switches to copy mode and when the session is switched, I have to close the copy mode and the the menu disappears. 

Similar thing happens with tpm, when installing plugins switches to copy mode. Is this how it is supposed to be?

**Comment by bruno-** [comment]
Hi,
that's definitely not how things are supposed to be.

Are you also using tmux with a hooks branch? If no, which tmux version are you using?

Since first opening this issue I have learned out that tmux hooks branch will eventually be merged into master, when the feature is finalized by Thomas Adam.
Until that is done, hooks branch is \*NOT\* supported because it's experimental and supporting it would be too much work.

**Comment by petermehle** [comment]
I dont use hooks branch (at least I think so) and tmux version is 1.9a

**Comment by bruno-** [comment]
Okay.. how did you install tmux?
Also, care to paste or link the contents of your `tmux.conf`?

**Comment by petermehle** [comment]
I am using this ppa: https://launchpad.net/~pi-rho/+archive/ubuntu/dev

**Comment by bruno-** [comment]
That should be ok. I upgraded to the latest tmux version (from source) and `prefix + g` still works fine.

Do you by any chance have something mapped to enter or Ctrl-m? Ctrl-m/enter is used internally to dismiss session list after the session is switched.

Also, how does the following command work:

    $ tmux switch-client -t <some session name>

Are you switched to the target session after you call that?

**Comment by petermehle** [comment]
switch client works as expected and there is nothing mapped to ctrl-m and enter

**Comment by bruno-** [comment]
Hey,
I think I figured this: you're running `emacs` copy mode, right?
If you're not sure, what is the output of this command `tmux show-option -gwv mode-keys`?

**Comment by petermehle** [comment]
no, vi mode

**Comment by petermehle** [comment]
my tmux.cong settings regarding copy mode (I still havent decided how to bind enter copy mode, so it is default)

setw -g mode-keys vi
unbind p
bind p paste-buffer
unbind -t vi-copy Enter
bind -t vi-copy 'v' begin-selection
bind -t vi-copy 'y' copy-selection

**Comment by bruno-** [comment]
Ah, this: `unbind -t vi-copy Enter`

Enter/C-m is used to dismiss session list output. If Enter is unbound, it's not working.
Can you please try setting this binding `tmux bind -t vi-copy Enter cancel` and then check if things are working?

Unfortunately, there's no way to invoke copy-mode commands directly without using key bindings. They have to be used, even in scripts and that causes issues if a user changes those key bindings.

**Comment by petermehle** [comment]
Yeah, this is the reason. If I remove it, then it works. If I am honest, I dont even know why it is there, probably I copied it from somewhere. Sorry for all the trouble

**Comment by bruno-** [comment]
No worries, I'm glad we found the reason behind this issue.
I'm going to start using `C-c` as a key to discard whatever is on the screen, so you can bring back `Return` if you want.

**Comment by petermehle** [comment]
great, thx for everything.

**Comment by bruno-** [comment]
Closing because it seems we fixed this.
